apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-07f991fa785cae6cf
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0fb9f12e33eeafb3e
      my-new-stack-PublicSubnet02:
        id: subnet-076775324a6c4f00b
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-04213b4ab9e115e88
      my-new-stack-PrivateSubnet02:
        id: subnet-001c79908221c7525

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true