apiVersion: v1
kind: Service
metadata:
  name: node-with-ddd-service
spec:
  type: NodePort
  selector:
    project: node-with-ddd
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 8080