apiVersion: v1
kind: Service
metadata:
  name: node-with-ddd-service
spec:
  type: LoadBalancer
  selector:
    project: node-with-ddd
  ports:
    - name: http
      port: 8080
      targetPort: 8080